### ISSUE TITLE
Merge request pipeline workflow fails with child pipelines

### ISSUE THREAD

**Issue by laslosobol** [laslosobol/Soft_Test_Lab1#6]
### Summary

It seems like child pipelines don't inherit the workflow:rules from the upstream pipeline. If you are attempting to include Workflows/MergeRequest-Pipelines.gitlab-ci.yml and create a pipeline from a merge request, the child pipeline will fail to create with "Downstream pipeline cannot be created, no stages/jobs for this pipeline." However, this works when running a pipeline on master.
![image](https://user-images.githubusercontent.com/45056502/109128632-56155c80-7758-11eb-9e1c-787ce348aef8.png)

.gitlab-ci.yml

```yaml
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

image: node:14-buster

build_pipeline:
  trigger:
    include:
      - project: 'gitlab-gold/cbledsoe-test/mr-template-test-downstream'
        ref: 'master'
        file: 'node/build/.application-build-stages.gitlab-ci.yml'
    strategy: depend
```

.application-build-stages.gitlab-ci.yml

```yaml
stages:
  - build

build:
  stage: build
  script:
    - echo "This is a build job"
```

If you *insert* a job, it *will* run but shouldn't be a requirement:

```yaml
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

image: node:14-buster

job_1:
   script:
     - echo "This should now run"

build_pipeline:
  trigger:
    include:
      - project: 'gitlab-gold/cbledsoe-test/mr-template-test-downstream'
        ref: 'master'
        file: 'node/build/.application-build-stages.gitlab-ci.yml'
    strategy: depend
```

Lastly, if you replace the included workflow and just add it directly, it still does not work and fails similarly:

.gitlab-ci.yml

```yaml
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: node:14-buster

build_pipeline:
  trigger:
    include:
      - project: 'gitlab-gold/cbledsoe-test/mr-template-test-downstream'
        ref: 'master'
        file: 'node/build/.application-build-stages.gitlab-ci.yml'
    strategy: depend
```
### What is the current *bug* behavior?

When including Workflows/MergeRequest-Pipelines.gitlab-ci.yml with parent-child pipelines, the pipeline fails with Downstream pipeline cannot be created.

### What is the expected *correct* behavior?

We would expect that when you use the merge requests pipelines workflow, it would work with parent child pipelines and the child pipeline would inherit rules.
